In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/vaish/OneDrive/Desktop/Dataset/Air_Quality - Air_Quality.csv")

In [5]:
df

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
0,172653,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2011,12/01/2010,25.30,NaN
1,172585,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2009,12/01/2008,26.93,NaN
2,336637,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,204,East New York,Annual Average 2015,01/01/2015,19.09,NaN
3,336622,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,103,Fordham - Bronx Pk,Annual Average 2015,01/01/2015,19.76,NaN
4,172582,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,104,Pelham - Throgs Neck,Annual Average 2009,12/01/2008,22.83,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
16213,130750,647,Outdoor Air Toxics - Formaldehyde,Annual average concentration,��g/m3,UHF42,211,Williamsburg - Bushwick,2005,01/01/2005,3.10,NaN
16214,130780,647,Outdoor Air Toxics - Formaldehyde,Annual average concentration,��g/m3,Borough,5,Staten Island,2005,01/01/2005,2.30,NaN
16215,131020,652,Cardiac and respiratory deaths due to Ozone,Estimated annual rate,"per 100,000",UHF42,504,South Beach - Tottenville,2005-2007,01/01/2005,7.50,NaN
16216,131026,652,Cardiac and respiratory deaths due to Ozone,Estimated annual rate,"per 100,000",Borough,5,Staten Island,2005-2007,01/01/2005,7.80,NaN
16217,325247,643,Annual vehicle miles traveled,million miles,per km2,CD,107,Upper West Side (CD7),2016,01/01/2016,50.00,NaN

In [ ]:
#Data Cleaning

In [15]:
df.describe()#inspecting the data

           Unique ID  Indicator ID   Geo Join ID    Data Value  Message
count   16218.000000  16218.000000  1.621800e+04  16218.000000      0.0
mean   372730.417746    427.803613  6.097103e+05     19.975917      NaN
std    215507.613560    110.921411  7.893388e+06     21.322349      NaN
min    121644.000000    365.000000  1.000000e+00      0.000000      NaN
25%    173211.250000    365.000000  2.020000e+02      9.050000      NaN
50%    325262.500000    375.000000  3.030000e+02     15.300000      NaN
75%    605270.750000    386.000000  4.040000e+02     26.037500      NaN
max    799868.000000    661.000000  1.051061e+08    424.700000      NaN

In [ ]:
df.info()#inspecting the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16218 entries, 0 to 16217
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unique ID       16218 non-null  int64
 1   Indicator ID    16218 non-null  int64
 2   Name            16218 non-null  object
 3   Measure         16218 non-null  object
 4   Measure Info    16218 non-null  object
 5   Geo Type Name   16218 non-null  object
 6   Geo Join ID     16218 non-null  int64
 7   Geo Place Name  16218 non-null  object
 8   Time Period     16218 non-null  object
 9   Start_Date      16218 non-null  object
 10  Data Value      16218 non-null  float64
 11  Message         0 non-null      float64
dtypes: float64(2), int64(3), object(7)
memory usage: 1.5+ MB

In [27]:
df.isnull().sum()#inspecting the data

Unique ID             0
Indicator ID          0
Name                  0
Measure               0
Measure Info          0
Geo Type Name         0
Geo Join ID           0
Geo Place Name        0
Time Period           0
Start_Date            0
Data Value            0
Message           16218
dtype: int64

In [33]:
# First we will convert the data type of message to object
df['Message']=df['Message'].astype('object')

#now we will fill the na values as no message 
df['Message']=df['Message'].fillna("no message")

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16218 entries, 0 to 16217
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unique ID       16218 non-null  int64
 1   Indicator ID    16218 non-null  int64
 2   Name            16218 non-null  object
 3   Measure         16218 non-null  object
 4   Measure Info    16218 non-null  object
 5   Geo Type Name   16218 non-null  object
 6   Geo Join ID     16218 non-null  int64
 7   Geo Place Name  16218 non-null  object
 8   Time Period     16218 non-null  object
 9   Start_Date      16218 non-null  object
 10  Data Value      16218 non-null  float64
 11  Message         16218 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 1.5+ MB

In [37]:
df.head()#here we can see message column has value"no message"

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
0,172653,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2011,12/01/2010,25.30,no message
1,172585,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2009,12/01/2008,26.93,no message
2,336637,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,204,East New York,Annual Average 2015,01/01/2015,19.09,no message
3,336622,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,103,Fordham - Bronx Pk,Annual Average 2015,01/01/2015,19.76,no message
4,172582,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,104,Pelham - Throgs Neck,Annual Average 2009,12/01/2008,22.83,no message

In [41]:
df.drop_duplicates(inplace=True)# drop the duplicate values

In [57]:
df['Start_Date']=pd.to_datetime(df['Start_Date'])#convert the date in general format and if null value is there it will place 'NaT'

In [59]:
df

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message,date
0,172653,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2011,2010-12-01,25.30,no message,2010-12-01
1,172585,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2009,2008-12-01,26.93,no message,2008-12-01
2,336637,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,204,East New York,Annual Average 2015,2015-01-01,19.09,no message,2015-01-01
3,336622,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,103,Fordham - Bronx Pk,Annual Average 2015,2015-01-01,19.76,no message,2015-01-01
4,172582,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,104,Pelham - Throgs Neck,Annual Average 2009,2008-12-01,22.83,no message,2008-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16213,130750,647,Outdoor Air Toxics - Formaldehyde,Annual average concentration,��g/m3,UHF42,211,Williamsburg - Bushwick,2005,2005-01-01,3.10,no message,2005-01-01
16214,130780,647,Outdoor Air Toxics - Formaldehyde,Annual average concentration,��g/m3,Borough,5,Staten Island,2005,2005-01-01,2.30,no message,2005-01-01
16215,131020,652,Cardiac and respiratory deaths due to Ozone,Estimated annual rate,"per 100,000",UHF42,504,South Beach - Tottenville,2005-2007,2005-01-01,7.50,no message,2005-01-01
16216,131026,652,Cardiac and respiratory deaths due to Ozone,Estimated annual rate,"per 100,000",Borough,5,Staten Island,2005-2007,2005-01-01,7.80,no message,2005-01-01
16217,325247,643,Annual vehicle miles traveled,million miles,per km2,CD,107,Upper West Side (CD7),2016,2016-01-01,50.00,no message,2016-01-01

In [ ]:
# Data Transformation

In [ ]:
# Min-Max Normalization

In [61]:
df['Normalized Value'] = (df['Data Value'] - df['Data Value'].min()) / (df['Data Value'].max() - df['Data Value'].min())

In [ ]:
#Now we will seperate the date into year and month column respectively

In [71]:
df['Year']=df['Start_Date'].dt.year

In [73]:
df['Month']=df['Start_Date'].dt.year

In [ ]:
#now we will convert the categorical data into numeric data using One hot encoding

In [81]:
data_encoded=pd.get_dummies(df,columns=['Name','Measure','Measure Info','Geo Type Name','Geo Place Name','Time Period'])
print(data_encoded)

       Unique ID  Indicator ID  Geo Join ID Start_Date  Data Value  \
0         172653           375          203 2010-12-01       25.30
1         172585           375          203 2008-12-01       26.93
2         336637           375          204 2015-01-01       19.09
3         336622           375          103 2015-01-01       19.76
4         172582           375          104 2008-12-01       22.83
...          ...           ...          ...        ...         ...
16213     130750           647          211 2005-01-01        3.10
16214     130780           647            5 2005-01-01        2.30
16215     131020           652          504 2005-01-01        7.50
16216     131026           652            5 2005-01-01        7.80
16217     325247           643          107 2016-01-01       50.00

          Message       date  Normalized Value  Year  Month  ...  \
0      no message 2010-12-01          0.059571  2010   2010  ...
1      no message 2008-12-01          0.063409  2008   2008  ...
2      no message 2015-01-01          0.044949  2015   2015  ...
3      no message 2015-01-01          0.046527  2015   2015  ...
4      no message 2008-12-01          0.053756  2008   2008  ...
...           ...        ...               ...   ...    ...  ...
16213  no message 2005-01-01          0.007299  2005   2005  ...
16214  no message 2005-01-01          0.005416  2005   2005  ...
16215  no message 2005-01-01          0.017660  2005   2005  ...
16216  no message 2005-01-01          0.018366  2005   2005  ...
16217  no message 2016-01-01          0.117730  2016   2016  ...

       Time Period_Winter 2011-12  Time Period_Winter 2012-13  \
0                           False                       False
1                           False                       False
2                           False                       False
3                           False                       False
4                           False                       False
...                           ...                         ...
16213                       False                       False
16214                       False                       False
16215                       False                       False
16216                       False                       False
16217                       False                       False

       Time Period_Winter 2013-14  Time Period_Winter 2014-15  \
0                           False                       False
1                           False                       False
2                           False                       False
3                           False                       False
4                           False                       False
...                           ...                         ...
16213                       False                       False
16214                       False                       False
16215                       False                       False
16216                       False                       False
16217                       False                       False

       Time Period_Winter 2015-16  Time Period_Winter 2016-17  \
0                           False                       False
1                           False                       False
2                           False                       False
3                           False                       False
4                           False                       False
...                           ...                         ...
16213                       False                       False
16214                       False                       False
16215                       False                       False
16216                       False                       False
16217                       False                       False

       Time Period_Winter 2017-18  Time Period_Winter 2018-19  \
0                           False                       False
1                           False                       False
2                           False                       False
3                           False                       False
4                           False                       False
...                           ...                         ...
16213                       False                       False
16214                       False                       False
16215                       False                       False
16216                       False                       False
16217                       False                       False

       Time Period_Winter 2019-20  Time Period_Winter 2020-21
0                           False                       False
1                           False                       False
2                           False                       False
3                           False                       False
4                           False                       False
...                           ...                         ...
16213                       False                       False
16214                       False                       False
16215                       False                       False
16216                       False                       False
16217                       False                       False

[16218 rows x 213 columns]