In [59]:
import numpy as np
import pandas as pd

In [61]:
df=pd.read_csv("C:/Users/vaish/OneDrive/Desktop/Dataset/heart.csv")

In [63]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
#Data cleaning
#Data Inspection

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [67]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [69]:
df.isna().sum()
#we can see that there are no null values

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [71]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [73]:
#removes duplicates value
df.drop_duplicates()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
# Error Handling

In [75]:
# we will check if the RestingBP is zero for any entry as it is practically impossible to have so
anomalous_bp = df[df['RestingBP'] == 0]
print("Entries with RestingBP = 0:\n", anomalous_bp)

Entries with RestingBP = 0:
      Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
449   55   M           NAP          0            0          0     Normal

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease
449    155              N      1.5     Flat             1

In [ ]:
# replace anomalous values with median

In [79]:
df['RestingBP'] = df['RestingBP'].replace(0, df['RestingBP'].median())

In [ ]:
# we will check if the Cholesterol is zero for any entry as it is practically impossible to have so

In [81]:
anomalous_chol=df[df['Cholesterol']==0]
print("Entries with Cholesterol=0:\n",anomalous_chol)

Entries with Cholesterol=0:
      Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
293   65   M           ASY        115            0          0     Normal
294   32   M            TA         95            0          1     Normal
295   61   M           ASY        105            0          1     Normal
296   50   M           ASY        145            0          1     Normal
297   57   M           ASY        110            0          1         ST
..   ...  ..           ...        ...          ...        ...        ...
514   43   M           ASY        122            0          0     Normal
515   63   M           NAP        130            0          1         ST
518   48   M           NAP        102            0          1         ST
535   56   M           ASY        130            0          0        LVH
536   62   M           NAP        133            0          1         ST

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease
293     93              Y      0.0     Flat             1
294    127              N      0.7       Up             1
295    110              Y      1.5       Up             1
296    139              Y      0.7     Flat             1
297    131              Y      1.4       Up             1
..     ...            ...      ...      ...           ...
514    120              N      0.5       Up             1
515    160              N      3.0     Flat             0
518    110              Y      1.0     Down             1
535    122              Y      1.0     Flat             1
536    119              Y      1.2     Flat             1

[172 rows x 12 columns]

In [ ]:
# replace anomalous values with 0

In [83]:
df['Cholesterol'] = df['Cholesterol'].replace(0, df['Cholesterol'].median())

In [ ]:
# now check if oldpeak value is negative as it is unrealistic

In [85]:
anomalous_oldpeak=df[df['Oldpeak']<0]
print("Entries with Oldpeak<0 :\n",anomalous_oldpeak)

Entries with Oldpeak<0 :
      Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
321   63   M           ASY        100          223          1     Normal
324   46   M           ASY        100          223          1         ST
325   42   M           ASY        105          223          1     Normal
326   45   M           NAP        110          223          0     Normal
331   56   M           ASY        115          223          1         ST
332   38   M           NAP        100          223          0     Normal
334   51   M           ASY        130          223          1     Normal
335   62   M            TA        120          223          1        LVH
352   56   M           ASY        120          223          0         ST
407   62   M           ASY        115          223          1     Normal
413   56   M           NAP        125          223          1     Normal
421   66   M           NAP        120          223          0         ST
512   35   M           NAP        123          161          0         ST

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease
321    109              N     -0.9     Flat             1
324    133              N     -2.6     Flat             1
325    128              Y     -1.5     Down             1
326    138              N     -0.1       Up             0
331     82              N     -1.0       Up             1
332    179              N     -1.1       Up             0
334    170              N     -0.7       Up             1
335    134              N     -0.8     Flat             1
352    100              Y     -1.0     Down             1
407     72              Y     -0.5     Flat             1
413     98              N     -2.0     Flat             1
421    120              N     -0.5       Up             0
512    153              N     -0.1       Up             0

In [ ]:
#now set the negative values to zero

In [87]:
df['Oldpeak'] = df['Oldpeak'].apply(lambda x: max(x, 0))

In [ ]:
# now we will encode the categorical data into numeric data using one hot encoding

In [89]:
heart_data_encoded = pd.get_dummies(df, columns=['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'])

In [91]:
print(heart_data_encoded)

     Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease  \
0     40        140          289          0    172      0.0             0
1     49        160          180          0    156      1.0             1
2     37        130          283          0     98      0.0             0
3     48        138          214          0    108      1.5             1
4     54        150          195          0    122      0.0             0
..   ...        ...          ...        ...    ...      ...           ...
913   45        110          264          0    132      1.2             1
914   68        144          193          1    141      3.4             1
915   57        130          131          0    115      1.2             1
916   57        130          236          0    174      0.0             1
917   38        138          175          0    173      0.0             0

     Sex_F  Sex_M  ChestPainType_ASY  ...  ChestPainType_NAP  \
0    False   True              False  ...              False
1     True  False              False  ...               True
2    False   True              False  ...              False
3     True  False               True  ...              False
4    False   True              False  ...               True
..     ...    ...                ...  ...                ...
913  False   True              False  ...              False
914  False   True               True  ...              False
915  False   True               True  ...              False
916   True  False              False  ...              False
917  False   True              False  ...               True

     ChestPainType_TA  RestingECG_LVH  RestingECG_Normal  RestingECG_ST  \
0               False           False               True          False
1               False           False               True          False
2               False           False              False           True
3               False           False               True          False
4               False           False               True          False
..                ...             ...                ...            ...
913              True           False               True          False
914             False           False               True          False
915             False           False               True          False
916             False            True              False          False
917             False           False               True          False

     ExerciseAngina_N  ExerciseAngina_Y  ST_Slope_Down  ST_Slope_Flat  \
0                True             False          False          False
1                True             False          False           True
2                True             False          False          False
3               False              True          False           True
4                True             False          False          False
..                ...               ...            ...            ...
913              True             False          False           True
914              True             False          False           True
915             False              True          False           True
916              True             False          False           True
917              True             False          False          False

     ST_Slope_Up
0           True
1          False
2           True
3          False
4           True
..           ...
913        False
914        False
915        False
916        False
917         True

[918 rows x 21 columns]